### ISSUE TITLE
No data return

### ISSUE THREAD

**Issue by nuno** [areknawo/Using-AG-Grid-React-UI-with-Remix.run#1]
No data return at table lever.
I have less than 100 records, maybe that is the issue here...

**Comment by areknawo** [comment]
If nothing appears in the table, check if you've got a filled database at *prisma/dev.db* and that you've got `DATABASE_URL="file:./dev.db"` env var in the *.env* file at the root. For me on Node v18.5.0 everything works well.

**Comment by nuno** [comment]
Thanks for your answer, yeah I have the data, it display in the other pages, I wanted to give a AG a try with remix.
I'm using:

   `remix version 1.6.1
    ag-grid-community 
     ag-grid-react 28.0.2 
     with react 18.2.0
      on node 16x`

Also I only have 10 records on db, I tried with cacheBlockSize={4} but no luck at least should filled the some rows?

 Im Wondering if this example could be upgraded to latest versions to make sure is working :) 

 Somehow i never get the data back if I console log the "posts.data" in the component before the return ,
but it output on server side and also if `JSON.stringify(posts.data)` at the end of the return before the last div.
maybe the versions?
 
 Thank you!

**Comment by areknawo** [comment]
Ok, the easiest solution I can suggest is to clone the repo and try to run it as-is. If this works, check out the database and make edits there. If everything's alright by that point, you can "re-apply" your edits on this new version (or compare it against the current in search of errors). It's hard for me to make guesses without seeing the code.

**Comment by jesseczko** [comment]
I also ran into a similar issue when I mocked the data to return ~ 10 items. See PR #2 as a fix. :-)
